VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IApp"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Sub OnLoad()
End Sub

Public Sub OnUnload()
End Sub

Public Sub Initialize(ByRef r_frm As Form)
End Sub

Public Property Get Title() As String

End Property

Public Property Get MainForm() As Form

End Property

Public Property Set MainForm(ByRef r_frm As Form)

End Property

