VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IInternetProtocolInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

 Sub CombineUrl(ByVal pwzBaseUrl As Long, ByVal pwzRelativeUrl As Long, ByVal dwCombineFlags As Long, ByVal pwzResult As Long, ByVal cchResult As Long, pcchResult As Long, ByVal dwReserved As Long)

End Sub

 Sub CompareUrl(ByVal pwzUrl1 As Long, ByVal pwzUrl2 As Long, ByVal dwCompareFlags As Long)

End Sub

 Sub ParseUrl(ByVal pwzUrl As Long, ByVal PARSEACTION As olelib.PARSEACTION, ByVal dwParseFlags As Long, ByVal pwzResult As Long, ByVal cchResult As Long, pcchResult As Long, ByVal dwReserved As Long)
   
End Sub

 Sub QueryInfo(ByVal pwzUrl As Long, ByVal OueryOption As olelib.QUERYOPTION, ByVal dwQueryFlags As Long, ByVal pBuffer As Long, ByVal cbBuffer As Long, pcbBuf As Long, ByVal dwReserved As Long)

End Sub
