Attribute VB_Name = "MCasts"
Function IAnimation(obj As IAnimation) As IAnimation
    Set IAnimation = obj
End Function

Public Function IFilter(obj As IFilter) As IFilter
    Set IFilter = obj
End Function

Public Function IFontDisp(obj As IFontDisp) As IFontDisp
    Set IFontDisp = obj
End Function

Public Function IPictureDisp(obj As IPictureDisp) As IPictureDisp
    Set IPictureDisp = obj
End Function

Function ISortHelper(obj As ISortHelper) As ISortHelper
    Set ISortHelper = obj
End Function

Function ISubclass(obj As ISubclass) As ISubclass
    Set ISubclass = obj
End Function

Function IUseFile(obj As IUseFile) As IUseFile
    Set IUseFile = obj
End Function

Function IUseFolder(obj As IUseFolder) As IUseFolder
    Set IUseFolder = obj
End Function

Function IUseRegItems(obj As IUseRegItems) As IUseRegItems
    Set IUseRegItems = obj
End Function

Function IVariantWalker(obj As IVariantWalker) As IVariantWalker
    Set IVariantWalker = obj
End Function

Function IVBContextMenu(obj As IVBContextMenu) As IVBContextMenu
    Set IVBContextMenu = obj
End Function

Function IVBContextMenu2(obj As IVBContextMenu2) As IVBContextMenu2
    Set IVBContextMenu2 = obj
End Function

Function IVBCreateTypeInfo(obj As IVBCreateTypeInfo) As IVBCreateTypeInfo
    Set IVBCreateTypeInfo = obj
End Function

Function IVBCreateTypeLib(obj As IVBCreateTypeLib) As IVBCreateTypeLib
    Set IVBCreateTypeLib = obj
End Function

Function IVBDispatch(obj As IVBDispatch) As IVBDispatch
    Set IVBDispatch = obj
End Function

Function IVBEnumIDList(obj As IVBEnumIDList) As IVBEnumIDList
    Set IVBEnumIDList = obj
End Function

Function IVBEnumSTATPROPSETSTG(obj As IVBEnumSTATPROPSETSTG) As IVBEnumSTATPROPSETSTG
    Set IVBEnumSTATPROPSETSTG = obj
End Function

Function IVBEnumSTATPROPSTG(obj As IVBEnumSTATPROPSTG) As IVBEnumSTATPROPSTG
    Set IVBEnumSTATPROPSTG = obj
End Function

Function IVBEnumSTATSTG(obj As IVBEnumSTATSTG) As IVBEnumSTATSTG
    Set IVBEnumSTATSTG = obj
End Function

Function IVBEnumVARIANT(obj As IVBEnumVARIANT) As IVBEnumVARIANT
    Set IVBEnumVARIANT = obj
End Function

Function IVBExtractIcon(obj As IVBExtractIcon) As IVBExtractIcon
    Set IVBExtractIcon = obj
End Function

Function IVBFileViewer(obj As IVBFileViewer) As IVBFileViewer
    Set IVBFileViewer = obj
End Function

Function IVBFileViewerSite(obj As IVBFileViewerSite) As IVBFileViewerSite
    Set IVBFileViewerSite = obj
End Function

Function IVBLockBytes(obj As IVBLockBytes) As IVBLockBytes
    Set IVBLockBytes = obj
End Function

Function IVBMalloc(obj As IVBMalloc) As IVBMalloc
    Set IVBMalloc = obj
End Function

Function IVBNewShortcutHook(obj As IVBNewShortcutHook) As IVBNewShortcutHook
    Set IVBNewShortcutHook = obj
End Function

Function IVBPersist(obj As IVBPersist) As IVBPersist
    Set IVBPersist = obj
End Function

Function IVBPersistFile(obj As IVBPersistFile) As IVBPersistFile
    Set IVBPersistFile = obj
End Function

Function IVBPersistStorage(obj As IVBPersistStorage) As IVBPersistStorage
    Set IVBPersistStorage = obj
End Function

Function IVBPersistStream(obj As IVBPersistStream) As IVBPersistStream
    Set IVBPersistStream = obj
End Function

Function IVBPropertySetStorage(obj As IVBPropertySetStorage) As IVBPropertySetStorage
    Set IVBPropertySetStorage = obj
End Function

Function IVBPropertyStorage(obj As IVBPropertyStorage) As IVBPropertyStorage
    Set IVBPropertyStorage = obj
End Function

Function IVBRootStorage(obj As IVBRootStorage) As IVBRootStorage
    Set IVBRootStorage = obj
End Function

Function IVBSequentialStream(obj As IVBSequentialStream) As IVBSequentialStream
    Set IVBSequentialStream = obj
End Function

Function IVBShellFolder(obj As IVBShellFolder) As IVBShellFolder
    Set IVBShellFolder = obj
End Function

Function IVBShellIcon(obj As IVBShellIcon) As IVBShellIcon
    Set IVBShellIcon = obj
End Function

Function IVBStorage(obj As IVBStorage) As IVBStorage
    Set IVBStorage = obj
End Function

Function IVBStream(obj As IVBStream) As IVBStream
    Set IVBStream = obj
End Function

Function IVBTypeComp(obj As IVBTypeComp) As IVBTypeComp
    Set IVBTypeComp = obj
End Function

Function IVBTypeInfo(obj As IVBTypeInfo) As IVBTypeInfo
    Set IVBTypeInfo = obj
End Function

Function IVBTypeLib(obj As IVBTypeLib) As IVBTypeLib
    Set IVBTypeLib = obj
End Function

Function IWindowsHelper(obj As IWindowsHelper) As IWindowsHelper
    Set IWindowsHelper = obj
End Function

