VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ICaptureBF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get CapturehWnd() As Long

End Property
Public Sub SelectionChanged(ByVal sPath As String)

End Sub
Public Property Let CaptureBrowseForFolder(ByRef c As Object)
   
End Property
Public Sub Unload()

End Sub

